name: Python Tests
run-name: Rest API Python Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: List files
        run: ls -al
        
